// Profile data for Mahaveer Amudhachandran
// Design: Executive Blueprint — Swiss International Typographic Style meets Modern Executive Portfolio

export const profile = {
  name: "Mahaveer Amudhachandran",
  title: "Director of Technology",
  subtitle: "AI-driven Composable Commerce Solutions",
  tagline: "Co-Founder, Metafyai | 16+ Years Enterprise Architecture",
  location: "Plainfield, Illinois, USA",
  email: "mahaveer.it@gmail.com",
  phone: "(+1) 313-502-4904",
  linkedin: "https://www.linkedin.com/in/mahaveer-amudhachandran",
  followers: "3,623",
  connections: "500+",
  summary: `Practice Head, Enterprise Architect, and Technology Leader with over 16 years of experience in Omnichannel Digital Transformation, Solution Architecture, and MACH-based composable commerce projects. Specializes in building high-performance teams from the ground up, KPI-driven delivery, presales, and innovation.

A trusted advisor to senior technologists and C-Level executives, delivering large-scale Omni-channel and marketplace commerce applications with a sharp focus on business and technology strategy. Extensive experience in P&L leadership, delivery leadership, project and program management governance, and developing enterprise omnichannel B2B, B2C, and Marketplace commerce solutions.`,
};

export const stats = [
  { label: "Years Experience", value: 18, suffix: "+" },
  { label: "Enterprise Clients", value: 17, suffix: "+" },
  { label: "LinkedIn Followers", value: 3623, suffix: "" },
  { label: "Certifications", value: 12, suffix: "+" },
];

export const experiences = [
  {
    id: 1,
    title: "Co-Founder & Director",
    company: "Metafyai",
    type: "Full-time",
    period: "Jan 2025 – Present",
    duration: "1 yr 3 mos",
    location: "United States",
    current: true,
    highlights: [
      "Leading vision, strategy, and growth of an AI-driven commerce solutions company",
      "Strategic Leadership: Setting company direction, forging high-impact partnerships, and pioneering scalable AI applications",
      "Business Development: Unlocking new market opportunities and driving revenue growth",
      "Operations & Execution: Overseeing end-to-end product development and team performance",
      "Innovation & Thought Leadership: Advocating for AI as a catalyst for business transformation",
    ],
    skills: ["Generative AI", "E-commerce", "Strategic Leadership", "AI Product Development"],
    url: "https://metafyai.com",
  },
  {
    id: 2,
    title: "Director of Technology",
    company: "Royal Cyber Inc.",
    type: "Full-time",
    period: "Apr 2023 – Present",
    duration: "3 yrs",
    location: "On-site",
    current: true,
    highlights: [
      "Leading the Digital Commerce technology practice with full accountability for architecture, delivery, and team performance",
      "Overseeing multiple enterprise engagements across B2B and B2C commerce platforms",
      "Driving technology strategy and innovation across SAP Commerce Cloud, commercetools, and MACH architectures",
      "Managing presales, client relationships, and cost proposals for major initiatives",
    ],
    skills: ["B2C", "SAP Commerce Cloud", "commercetools", "Enterprise Architecture", "MACH Architecture"],
    url: "https://royalcyber.com",
  },
  {
    id: 3,
    title: "Product Head / Lead of Digital Commerce",
    company: "Royal Cyber Inc.",
    type: "Full-time",
    period: "Apr 2020 – Jul 2023",
    duration: "3 yrs 4 mos",
    location: "Chicago, Illinois, USA",
    current: false,
    highlights: [
      "Led development, testing, and cross-functional teams for enterprise commerce projects",
      "Provided vision-based strategic advisory to clients scaling e-commerce globally",
      "Headed the Product Development/Research team building AI/ML and AR-powered commerce products",
      "Led technology decisions and product selections through robust evaluations and Proof of Concepts",
      "Developed 6 proprietary AI-powered products including Natural Language Search, Visual AI Search, and Express Checkout",
    ],
    skills: ["B2C", "B2B", "AI/ML", "Product Development", "Team Leadership"],
    url: "https://royalcyber.com",
  },
  {
    id: 4,
    title: "NextGen DTC Platform",
    company: "Mars (M&M'S)",
    type: "Full-time",
    period: "Mar 2024 – May 2024",
    duration: "3 mos",
    location: "Illinois, USA (Hybrid)",
    current: false,
    highlights: [
      "Implemented MACH-based composable commerce architecture for multi-brand DTC platform",
      "Built decoupled architecture using event-based integration patterns, GraphQL, and APIs",
      "Delivered multi-brand, multi-channel DTC development and support functions for M&M'S",
      "Ensured scalability to drive sustainable growth and cost optimization",
    ],
    skills: ["commercetools", "MACH Architecture", "GraphQL", "Multi-brand Commerce"],
    url: "https://www.mms.com/",
  },
  {
    id: 5,
    title: "Customer Service Accelerator",
    company: "Sportsman's Guide",
    type: "Full-time",
    period: "Dec 2023 – May 2024",
    duration: "6 mos",
    location: "Illinois, USA (Hybrid)",
    current: false,
    highlights: [
      "Spearheaded design and implementation of a unified interface for all sales and customer interactions",
      "Built Customer Service Accelerator with 360° customer profile view, cart/order management, and ticketing",
      "Led team providing personalized support using customer data insights",
      "Monitored performance metrics to continuously improve service delivery",
    ],
    skills: ["commercetools", "Contentstack", "Customer Experience", "Service Architecture"],
    url: "https://www.sportsmansguide.com/",
  },
  {
    id: 6,
    title: "Composable Commerce Solution Architect",
    company: "Nerivio",
    type: "Full-time",
    period: "Jun 2023 – Dec 2023",
    duration: "7 mos",
    location: "Illinois, USA (Remote)",
    current: false,
    highlights: [
      "Developed intuitive CX using Frontastic with headless modules from commercetools",
      "Enhanced customer experience with product search and custom price filters using Algolia",
      "Integrated end-to-end order management workflow with SAP ERP",
    ],
    skills: ["Algolia", "Contentful", "commercetools", "Frontastic", "SAP ERP"],
    url: "https://nerivio.com/",
  },
  {
    id: 7,
    title: "Composable Commerce Solution Architect",
    company: "Dr. Reddy's Laboratories",
    type: "Full-time",
    period: "Nov 2022 – Jun 2023",
    duration: "8 mos",
    location: "Illinois, USA (Remote)",
    current: false,
    highlights: [
      "Built pharma marketplace allowing multiple vendors to sell on the platform",
      "Automated all manual processes in the internal procurement journey",
      "Created discovery platform for buyers to browse product offerings",
      "Integrated end-to-end order management with SAP ERP",
    ],
    skills: ["Algolia", "Google Cloud Platform", "Contentful", "commercetools"],
    url: "https://www.drreddys.com/",
  },
  {
    id: 8,
    title: "Composable Commerce Solution Architect",
    company: "Rich Products Corporation",
    type: "Full-time",
    period: "Jan 2022 – Oct 2022",
    duration: "10 mos",
    location: "Illinois, USA (Remote)",
    current: false,
    highlights: [
      "Implemented flexible data model for multi-brand food corporation D2C business",
      "Developed seamless D2C model using headless and Microservices-based approach with commercetools",
      "Implemented catalog management, customer groups, contracts, new currencies and languages",
    ],
    skills: ["commercetools", "WordPress", "Microservices", "D2C"],
    url: "https://www.richs.com/",
  },
  {
    id: 9,
    title: "Composable Commerce Solution Architect",
    company: "Breville | Commercial",
    type: "Full-time",
    period: "Apr 2020 – Nov 2021",
    duration: "1 yr 8 mos",
    location: "Illinois, USA (Remote)",
    current: false,
    highlights: [
      "Designed and executed Subscription-based Product modeling system in commercetools",
      "Contributed to AWS cloud infrastructure design with Terraform DevOps pipelines",
      "Developed microservices for integration between Adobe AEM and commercetools",
      "Implemented Cache and CDN strategies to enhance system performance",
      "Adhered to MACH principles throughout the implementation",
    ],
    skills: ["commercetools", "AWS", "Terraform", "Pimcore", "Salesforce CRM Analytics", "Adobe AEM"],
    url: "https://www.breville.com/",
  },
  {
    id: 10,
    title: "Composable Commerce Solution Architect",
    company: "JSW Steel",
    type: "Full-time",
    period: "Jan 2020 – Sep 2020",
    duration: "9 mos",
    location: "Illinois, USA (Remote)",
    current: false,
    highlights: [
      "Designed and built complex B2B application with various integrations",
      "Implemented numerous customizations and API extensions in commercetools for B2B features",
      "Developed Microservices Rest/GraphQL API for company, Employee, and Quote management",
      "Integrated Auth0 for user login in VUE Storefront",
    ],
    skills: ["commercetools", "Algolia", "SAP ERP", "Auth0", "GraphQL", "Vue Storefront"],
    url: "https://jswsteelformsme.in/",
  },
  {
    id: 11,
    title: "SAP Commerce Solutions Architect",
    company: "OMEGA Engineering",
    type: "Full-time",
    period: "Jul 2018 – Jan 2020",
    duration: "1 yr 7 mos",
    location: "Illinois, USA (Remote)",
    current: false,
    highlights: [
      "Led design and delivery for B2B Product catalog, Web Content catalog, and Order management",
      "Managed successful migration from SAP Commerce 6.4 to SAP Commerce 1905",
      "Designed SAP Commerce for Multi-Country Rollouts (UK, Germany, China, France)",
      "Integrated 3rd party services like DELL Boomi, Salesforce, Solr, and Cyber Source",
    ],
    skills: ["SAP Commerce Cloud", "Salesforce", "DELL Boomi", "Solr"],
    url: "https://www.omega.com/",
  },
  {
    id: 12,
    title: "SAP Commerce Solution Architect",
    company: "Royal Cyber Inc.",
    type: "Full-time",
    period: "Apr 2018 – Mar 2020",
    duration: "2 yrs",
    location: "Chicago, Illinois, USA",
    current: false,
    highlights: [
      "Architected SAP Commerce solutions for multiple enterprise clients",
      "Led B2C and B2B platform implementations",
    ],
    skills: ["SAP Commerce Cloud", "B2C", "B2B"],
    url: "https://royalcyber.com",
  },
  {
    id: 13,
    title: "Hybris Lead Architect",
    company: "Wipro Technologies (at Pep Boys)",
    type: "Full-time",
    period: "Aug 2016 – Apr 2018",
    duration: "1 yr 9 mos",
    location: "Philadelphia, USA",
    current: false,
    highlights: [
      "Responsible for B2C Product catalog, Web Content catalog, Order management, and SAP ECC integration",
      "Integrated 3rd party services like SAP, EPICOR, PayPal, Bazar Voice, and Cyber Source",
      "Designed and developed Responsive UI Design in Hybris",
    ],
    skills: ["Hybris 6.4", "SAP HANA", "SAP ECC", "PayPal"],
    url: "https://www.pepboys.com/",
  },
  {
    id: 14,
    title: "Hybris Architect",
    company: "Wipro Technologies (at Federal Mogul)",
    type: "Full-time",
    period: "Sep 2014 – Jul 2016",
    duration: "1 yr 11 mos",
    location: "Detroit, USA",
    current: false,
    highlights: [
      "Gathered requirements and prepared architecture design based on Hybris 5.3",
      "Integrated SAP SNP, SAP CRM for Loyalty and Training, SAP ECC, and Cyber Source",
    ],
    skills: ["Hybris 5.3", "Oracle DB", "SAP ECC", "Mainframe"],
    url: "https://www.fmmotorparts.com/",
  },
];

export const certifications = [
  {
    name: "commercetools Certified Associate Java Developer",
    issuer: "commercetools",
    date: "Feb 2021",
    credentialId: "aWnGBtrV4S",
    skills: ["commercetools", "React.js", "Java"],
    color: "#00b8d9",
  },
  {
    name: "SAP Certified Development Professional – SAP Commerce Cloud 1905 Developer",
    issuer: "SAP Hybris",
    date: "Mar 2020",
    credentialId: "—",
    skills: ["SAP Commerce Cloud", "B2C"],
    color: "#0070f3",
  },
  {
    name: "Kyma – A Flexible Way to Connect and Extend Applications",
    issuer: "openSAP / SAP SE",
    date: "Apr 2020",
    credentialId: "Score: 93.3%",
    skills: ["Kyma", "SAP BTP"],
    color: "#0070f3",
  },
  {
    name: "What Is Generative AI?",
    issuer: "LinkedIn Learning",
    date: "Jul 2023",
    credentialId: "f5dac16bce7d...",
    skills: ["Generative AI", "Artificial Intelligence"],
    color: "#0a66c2",
  },
  {
    name: "AWS and React: Creating Full-Stack Apps",
    issuer: "LinkedIn Learning",
    date: "Feb 2021",
    credentialId: "—",
    skills: ["AWS", "React"],
    color: "#ff9900",
  },
  {
    name: "Fundamentals of Generative AI",
    issuer: "Microsoft Learn",
    date: "2023",
    credentialId: "—",
    skills: ["Generative AI", "Azure AI"],
    color: "#00a4ef",
  },
  {
    name: "Fundamentals of Azure OpenAI Service",
    issuer: "Microsoft Learn",
    date: "2023",
    credentialId: "—",
    skills: ["Azure OpenAI", "AI"],
    color: "#00a4ef",
  },
  {
    name: "Oracle Java Certification 1.6",
    issuer: "Oracle",
    date: "—",
    credentialId: "—",
    skills: ["Java"],
    color: "#f80000",
  },
  {
    name: "Hybris Core Developer v5.0",
    issuer: "SAP Hybris",
    date: "—",
    credentialId: "—",
    skills: ["SAP Hybris"],
    color: "#0070f3",
  },
];

export const skillCategories = [
  {
    category: "Commerce Platforms",
    skills: ["SAP Commerce Cloud", "commercetools", "VTEX Platform", "Optimizely Commerce", "Contentful", "Contentstack", "Pimcore"],
  },
  {
    category: "Architecture",
    skills: ["MACH Architecture", "Enterprise Architecture", "Composable Commerce", "Microservices", "Event-Driven Architecture", "API-first Design", "GraphQL", "REST APIs"],
  },
  {
    category: "Cloud & DevOps",
    skills: ["Google Cloud Platform (GCP)", "Amazon Web Services (AWS)", "Docker", "Kubernetes", "Terraform", "CI/CD Pipelines"],
  },
  {
    category: "AI & Emerging Tech",
    skills: ["Generative AI", "Azure OpenAI", "Natural Language Processing", "Visual AI Search", "AI Product Recommendations", "AR Commerce"],
  },
  {
    category: "Programming & Web",
    skills: ["Java / J2EE", "Spring MVC", "React.js", "Vue.js", "Node.js", "GraphQL", "HTML5 / CSS3", "JavaScript"],
  },
  {
    category: "Search & Data",
    skills: ["Algolia", "Apache Solr", "Oracle DB", "MySQL", "SAP HANA", "PostgreSQL"],
  },
];

export const clients = [
  { name: "MARS (M&M'S)", industry: "Consumer Goods", platform: "commercetools" },
  { name: "Dr. Reddy's Laboratories", industry: "Pharmaceuticals", platform: "commercetools + GCP" },
  { name: "Breville", industry: "Kitchen Appliances", platform: "commercetools + AWS" },
  { name: "JSW Steel", industry: "Manufacturing", platform: "commercetools" },
  { name: "Omega Engineering", industry: "Instrumentation", platform: "SAP Commerce Cloud" },
  { name: "Sportsman's Guide", industry: "Retail", platform: "commercetools" },
  { name: "Nerivio", industry: "Healthcare", platform: "commercetools" },
  { name: "Rich Products", industry: "Food & Beverage", platform: "commercetools" },
  { name: "Pep Boys", industry: "Automotive Retail", platform: "SAP Hybris" },
  { name: "Federal-Mogul", industry: "Automotive Parts", platform: "SAP Hybris" },
  { name: "Akzo Nobel", industry: "Coatings", platform: "SAP Hybris" },
  { name: "Maxis Communications", industry: "Telecom", platform: "SAP Hybris" },
  { name: "1800 Flowers", industry: "Gifting", platform: "Java/J2EE" },
  { name: "Wal-Mart", industry: "Retail", platform: "Java/J2EE" },
];

export const coreCompetencies = [
  {
    area: "Technology Strategy & Governance",
    description: "Define and execute technology strategy for composable commerce programs across multiple customer engagements, aligning architecture decisions with business outcomes and delivery timelines.",
    icon: "🎯",
    timePercent: 15,
    hoursPerWeek: 6,
  },
  {
    area: "Solution Architecture & Integration",
    description: "Own end-to-end solution architecture including domain decomposition, service boundaries, integration strategy (ERP, OMS, PIM, CRM, payments, tax, shipping, search, identity), and reference architecture maintenance.",
    icon: "🏗️",
    timePercent: 25,
    hoursPerWeek: 10,
  },
  {
    area: "Engineering Oversight & Mentorship",
    description: "Lead code/design reviews, enforce standards, govern CI/CD pipelines, and mentor senior engineers, tech leads, and architects on architecture thinking and delivery execution.",
    icon: "👨‍💻",
    timePercent: 20,
    hoursPerWeek: 8,
  },
  {
    area: "Platform Practice Ownership",
    description: "Own the commercetools, Optimizely, and Shopify practices — developing playbooks, reusable patterns, accelerators, and platform decisions that scale execution across teams.",
    icon: "🔧",
    timePercent: 10,
    hoursPerWeek: 4,
  },
  {
    area: "AI & Agentic Commerce Leadership",
    description: "Lead agentic commerce capabilities (shopping/service agents), RAG pipelines for product/policy/order knowledge, AEO/GEO strategy for AI-driven discoverability, and AI observability/safety controls.",
    icon: "🤖",
    timePercent: 10,
    hoursPerWeek: 4,
  },
  {
    area: "Quality & Non-Functional Leadership",
    description: "Define test strategy, SIT/UAT readiness, performance/load testing coordination, go-live readiness, and non-functional governance for scalability, availability, resiliency, and security.",
    icon: "✅",
    timePercent: 10,
    hoursPerWeek: 4,
  },
  {
    area: "Production Oversight & Stability",
    description: "Guide incident triage, root cause analysis, remediation planning, and stability improvements across live commerce platforms.",
    icon: "🛡️",
    timePercent: 10,
    hoursPerWeek: 4,
  },
];

export const aiLeadership = [
  {
    title: "Agentic Commerce",
    description: "Define and lead agentic commerce capabilities — shopping and service agents integrated with commerce platforms using tool-calling workflows and approvals for high-risk actions.",
    tag: "AI Strategy",
  },
  {
    title: "RAG Pipeline Architecture",
    description: "Architect and govern Retrieval-Augmented Generation (RAG) pipelines for product, policy, and order knowledge — including embeddings strategy, relevance tuning, evaluation metrics, and access controls.",
    tag: "Generative AI",
  },
  {
    title: "AEO / GEO Strategy",
    description: "Drive Answer Engine Optimization and Generative Engine Optimization so product and content experiences are discoverable by AI-powered answer engines — structured data, entity modeling, content governance, and freshness SLAs.",
    tag: "AEO · GEO",
  },
  {
    title: "Composable Platform Partnerships",
    description: "Build and manage platform composable partnerships — defining integration standards, joint solution patterns, adoption roadmaps, reference architectures, certification/enablement, and reusable integration kits.",
    tag: "Ecosystem",
  },
];

export const education = [
  {
    degree: "B. Tech – Information Technology",
    institution: "Coimbatore Institute of Technology (CIT)",
    university: "Anna University, Tamil Nadu",
    year: "2007",
    score: "CGPA: 7.12",
  },
  {
    degree: "Diploma – Information Technology",
    institution: "Swamy Abedhanandha Polytechnic College",
    university: "Thellar, Tamil Nadu",
    year: "2004",
    score: "94.16%",
  },
];

export const products = [
  {
    name: "MetafyAI – AEO/GEO",
    description: "AI-powered Answer Engine Optimization and Generative Engine Optimization platform — helping brands get discovered and ranked inside AI-generated answers and LLM-driven search experiences.",
    icon: "🤖",
    url: "https://app.metafyai.com/",
  },
  {
    name: "EchoX – AI Recommendations",
    description: "Intelligent product recommendation engine that learns from behavioral signals to deliver hyper-personalized commerce experiences and drive revenue uplift.",
    icon: "📡",
    url: "https://echorecommend.com/",
  },
  {
    name: "StudioX – Ship Storefronts in Minutes, Not Months",
    description: "AI-accelerated storefront builder enabling brands to design, configure, and launch composable commerce storefronts at unprecedented speed without compromising quality.",
    icon: "🚀",
    url: "",
  },
  {
    name: "Customer Service Accelerator",
    description: "Unified customer service interface with 360° customer profile view, cart/order management, and ticketing — available on the commercetools Marketplace.",
    icon: "🎧",
    url: "https://marketplace.commercetools.com/accelerators/customer-service-accelerator",
  },
  {
    name: "AI-Powered Natural Language Search",
    description: "Semantic search engine leveraging AI/ML for intelligent product discovery across commerce platforms",
    icon: "🔍",
  },
  {
    name: "Visual AI Search",
    description: "Image-based product search using computer vision and augmented reality technology",
    icon: "👁️",
  },
  {
    name: "AI Product Recommendations",
    description: "Personalized recommendation engine driven by machine learning and behavioral data",
    icon: "🎯",
  },
  {
    name: "Express Checkout",
    description: "AI-assisted, streamlined checkout experience reducing cart abandonment",
    icon: "⚡",
  },
  {
    name: "Product 360 Configure (3dddplus)",
    description: "3D product visualization and configuration tool for immersive shopping experiences",
    icon: "🔄",
  },
  {
    name: "Commerce Subscription Engine",
    description: "Subscription-based product modeling and recurring order management system",
    icon: "📦",
  },
];
